### ISSUE TITLE
Phase 1 known issues checklist

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#1768]
## A. Phase 1 beacon chain for legacy
- [ ] 1. Possible beacon chain changes for phase 1  #1825 
- [ ] 2. Exit fee [#1521](https://github.com/ethereum/eth2.0-specs/issues/1521)
- [ ] 3. Maximum reversions: Enshrine dynamic weak subjectivity reversion period into fork choice rule ("second finality mechanism"): [#1520](https://github.com/ethereum/eth2.0-specs/issues/1520) and [#1053](https://github.com/ethereum/eth2.0-specs/issues/1053)

## B. Phase 1 beacon chain for shards
- [ ] 1. Shard chain slashing
- [ ] 2. Rewards on shards [#1280](https://github.com/ethereum/eth2.0-specs/issues/1520) and [#1053](https://github.com/ethereum/eth2.0-specs/issues/1280)
- [x] 3. Implement `get_start_shard` logic (#1858)
- [ ] 4. Slowly rotating shard committees for stabilizing subnets
- [x] 5. Add `Shard` field to `AttestationData`
- [x] 6. Use non-length mixins root for `shard_data_roots`
- [ ] 7. Decide how to change active shard count (#2033)

## C. Phase 1 shard chain
- [x] 1. **[shard chain fork choice rule]** move `get_winning_proposal` logic to it. Maintain canonical shard chain upon (i) receiving new shard block (ii) new beacon chain block (ii) time tick. (#1773) 
- [x] 2. **[shard chain transition]** Add `shard_transition_digest` wrapper. Currently we have `hash(hash_tree_root(shard_state) + beacon_parent_root + shard_body_root)`
- [ ] 3. **[data availability]** Inefficiencies in data availability proofs [#1194](https://github.com/ethereum/eth2.0-specs/issues/1194) (outdated???)
- [ ] 4. **[data availability]** Generating data availability roots from shard block roots [#1438](https://github.com/ethereum/eth2.0-specs/issues/1438)
- [x] 5. [0.001 bit proof of custody](https://ethresear.ch/t/a-0-001-bit-proof-of-custody/7409) (#1889)

## D. Phase 1 fork choice rule
- [ ] 1. Separate beacon and shard logic
- [ ] 2. Use GHOST instead of LMD-GHOST for shard fork choice rule

**Comment by terencechain** [comment]
Not sure if this categorize as a beacon chain known issue, I'm curious to know if we should add `Shard` as a first class citizen in `AttestationData`, whether to replace `CommitteeIndex` or be explicit about both

**Comment by vbuterin** [comment]
Add an item: move to Dankrad's [0.001 bit proof of custody](https://ethresear.ch/t/a-0-001-bit-proof-of-custody/7409)?
