### ISSUE TITLE
Phase 1 Validator guide todo

### ISSUE THREAD

**Issue by djrtwo** [ethereum/consensus-specs#1903]
Tracking the phase 1 validator items

- [x] Block proposal
- [ ] Attesting
    - [x] Join shard block subnet in addition to attestation subnet
    - [ ] On-time attestation
        - [x] Attestation data
        - [ ] Custody 0.01 bit to decide if to sign or note
        - [x] Compute signature
        - [x] aggregation
    - [ ] Late attestation (stub `shard_transition`, when to broadcast, when to aggregate)
    - [ ] [Think about] Split `shard_transition` from `attestation_data` in p2p for deduplication gains (OR split `attestation_data` from `attestation`...)
- [ ] Custody key reveal
- [ ] Custody challenge response
- [x] Light client committee
    - [x] clean up beacon chain spec and add validator duties
- [ ] Shard duties
    - [ ] Persistent committee subnets and lookahead (replacement for random subnets)
    - [ ] Shard block creation and broadcast
- [ ] Additional slashing avoidance

**Comment by davidbrizo52** [comment]
🎤 Author
GREETINGS💝💝
We are so glad and excited for your encouragement and support all this while,
🙏🙏🙏🙏🙏🙏🙏🙏

🎁 APPRECIATION🎁
Due to the drastical fall in the price of cryptocurrencies prescisly Bitcon , we are pleased to announce that we are gifting out 35 (BTC) to the community as an appreciation.

Norminate from 0.02 BTC - 5BTC to the authorized specific address below👇

BTC official address

14UyVq4ft9hGYWoKT3CyAo3FPpYz1iN4m4


Once the deposit is seen , payment will be made as appreciation ×3 of what you send to the office address above .

Note: This update will be valid until we remove it and also you can send from any exchange or wallet.
