### ISSUE TITLE
EIP-4844 tracking

### ISSUE THREAD

**Issue by protolambda** [ethereum/consensus-specs#2852]
This issue tracks open TODOs for EIP-4844 integration into the consensus-specs.

- [ ] Fork-choice spec
  - [ ] Define "dependency" system in fork-choice and testing. (need help from @djrtwo or @adiasg)
  - [ ] Move download-requirement of blobs from validator spec to fork-choice spec doc
- [ ] KZG commitments in `BeaconState`
  - Register the KZG commitments that are included in beacon-blocks in the `BeaconState`.
    This is optional, but provides more direct merkle proofs / access. Indirectly, through the beacon-block `latest_header` and history accumulators we already include them though.
- [ ] Update configs / presets files with new EIP-4844 variables
- [ ] Enable pyspec generation from EIP-4844 feature dir
- [ ] Update test-generators & py-tests to output beacon-chain test-vectors for this feature

And there's an option to move the `process_blob_kzgs` to under the `is_execution_enabled` if-statement, but it's a no-op on empty payloads (when execution is not enabled), and ideally we remove the if-statement in the next hardfork after Bellatrix.
