### ISSUE TITLE
`docs` improvements tracking

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#3325]
### Online viewer
-  [ ] Dead links: some links to files in tests/ folder are still wrong. The simplest solution is using absolute links here. Anothor solution is to arrange the tests docs all together.
- [ ] Align `anchor_linenums`: somehow the line numbers of code block are not vertically aligned well
- [ ] Allow selecting consensus fork in a corner: probably need to write a custom plug-in / extension

**Comment by leolara** [comment]
I am closing this issue because it seems stale. Please, do not hesitate to reopen it if this is a mistake
