### ISSUE TITLE
Enhance Deneb tests

### ISSUE THREAD

**Issue by hwwhww** [ethereum/consensus-specs#3458]
A spreadsheet of current Deneb new test cases: [link](https://docs.google.com/spreadsheets/d/1nH08GLmNba_Hjj96Q1D24-MBw9LWVszdVttjV159i9Q/edit?usp=sharing)

TODOs:
- [x] enhance the randomized test cases: #3457
- [x] mixed tx tests: #3457 
- [x] fork choice tests: #3463
- [x] more tx length tests #3459
- [x] EIP-7514 fork boundary tests
- [x] EIP-7514 from high to low churn rate 
- [x] #3539
...more
